esp_toml_version = 1.0

firmware_images_url = "https://truedo.github.io/esp-launchpad/firmware/"

supported_apps = ["ZumiMini_1_21"]

[ZumiMini_1_21]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "Zumini_main_merge_1_21.bin"


